### ISSUE TITLE
getting error during  wit add-dep <package-name> command

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/wit#154]
As per your tutorial on adding dependency of package in wit, if we run-
```
 wit add-dep <$BAR_PATH or package-name>
```
it is giving an error like following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shraddha/wit/lib/wit/__main__.py", line 11, in <module>
    main()
  File "/home/shraddha/wit/lib/wit/main.py", line 135, in main
    add_dep(ws, args)
  File "/home/shraddha/wit/lib/wit/main.py", line 220, in add_dep
    req_dep = dependency_from_tag(ws.root, args.pkg)
  File "/home/shraddha/wit/lib/wit/main.py", line 208, in dependency_from_tag
    source = repo.get_remote()
  File "/home/shraddha/wit/lib/wit/gitrepo.py", line 139, in get_remote
    self._git_check(proc)
  File "/home/shraddha/wit/lib/wit/gitrepo.py", line 248, in _git_check
    raise GitError(msg)
wit.gitrepo.GitError: Command [git remote get-url origin] exited with non-zero exit status [128]
stdout: []
stderr: [fatal: No such remote 'origin']
```
Please suggest me the solution.

**Comment by ShraddhaDevaiya** [comment]
i have checked that wit version,  which is 
wit 0.10.1-14-ga7c9344.
I have named that package 'bar', which is the git repository created by me as per your tutorial, you can see that in tutorial page itself. I have followed the same steps, still getting this error , at the time of adding that package in the workspace.

**Comment by ShraddhaDevaiya** [comment]
I have tried on Ubuntu Linux 19.04 and git version is 2.20.1 . and wit version is  v0.10.1, as I informed you earlier.

**Comment by richardxia** [comment]
From taking a closer look at the stack trace in your original post, I believe the issue is you ran the `git init bar` repository within in your wit workspace and not outside of the wit workspace. In the tutorial, the `cd ..` command is meant to take you outside of the workspace directory (`myws/`) so that the subsequent commands will create a `bar` repository outside of `myws/`.

To fix the issue, please move the `bar/` directory within the workspace to a location outside of the workspace. Alternatively, you could try running the tutorial from scratch but pay very careful attention to the `cd ..` command, since it is essential. Please let me know if this resolves the issue for you.

In any case, wit should provide a clearer error message for this edge case and at least describe possible solutions to the problem.

**Comment by ShraddhaDevaiya** [comment]
Yeah, it is working now, means we need to add dependency from the workspace itself. Thanks !
